[build]
  base = "src/ui"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://your-api.onrender.com"
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://your-api.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000