[build]
builder = "dockerfile"

[deploy]
startCommand = "python -m uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"
ENVIRONMENT = "production"