services:
  - type: web
    name: conversation-evaluation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HUGGINGFACE_TOKEN
        sync: false
      - key: PYTHONPATH
        value: "/opt/render/project/src"
    healthCheckPath: /health